### ISSUE TITLE
Error Project not found 'go-graphql$dev'

### ISSUE THREAD

**Issue by thanhngvpt** [prisma/prisma-examples#294]
Hi all,
I've cloned this repo to get starting with prisma and go. After run server by command `go run server/server.go` then try to create a post i got error `runtime error: invalid memory address or nil pointer dereference`  I print the error on this 

```

func (r *mutationResolver) CreateDraft(ctx context.Context, title string, content string, authorEmail string) (prisma.Post, error) {
	post, err := r.Prisma.CreatePost(prisma.PostCreateInput{
		Title:   title,
		Content: content,
		Author: prisma.UserCreateOneWithoutPostsInput{
			Connect: &prisma.UserWhereUniqueInput{Email: &authorEmail},
		},
	}).Exec(ctx)
	fmt.Println("err: ", err) // this show error `err:  graphql: Project not found: 'go-graphql$dev'`
	return *post, err
}
```

My prisma.yml

```
# Specifies the HTTP endpoint of your Prisma API.
endpoint: http://localhost:4466

# Defines your models, each model is mapped to the database as a table.
datamodel: datamodel.prisma

# Specifies the language and directory for the generated Prisma client.
generate:
  - generator: go-client
    output: ../prisma-client/

# Ensures Prisma client is re-generated after a datamodel change.
hooks:
  post-deploy:
    - prisma generate

# # Seeds initial data into the database by running a script.
# seed:
#   run: go run seed.go
```

Please help me check. Thank you
